spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/retail
    username: toteall
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
